# Generated by Django 4.2.30 on 2026-08-01 13:46

import apps.absences.models
import apps.absences.validators
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('employees', '0004_alter_employee_profile_photo'),
        ('tenants', '0002_alter_organization_logo'),
    ]

    operations = [
        migrations.CreateModel(
            name='AbsenceReason',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('requires_certificate', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenants.organization')),
            ],
            options={
                'ordering': ['name'],
            },
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Absence',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField()),
                ('employee_comment', models.TextField(blank=True)),
                ('justification_file', models.FileField(blank=True, max_length=255, null=True, upload_to=apps.absences.models.justification_path, validators=[apps.absences.validators.validate_justification_file])),
                ('status', models.CharField(choices=[('UNJUSTIFIED', 'Non justifiée'), ('PENDING_REVIEW', 'En attente de validation'), ('JUSTIFIED', 'Justifiée'), ('REJECTED', 'Rejetée')], default='UNJUSTIFIED', max_length=15)),
                ('reviewer_comment', models.TextField(blank=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('is_auto_detected', models.BooleanField(default=False)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='absences', to='employees.employee')),
                ('reason', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='absences', to='absences.absencereason')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='absences_reviewed', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenants.organization')),
            ],
            options={
                'ordering': ['-date'],
            },
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddConstraint(
            model_name='absencereason',
            constraint=models.UniqueConstraint(fields=('tenant', 'name'), name='absences_reason_tenant_name_uniq'),
        ),
        migrations.AddConstraint(
            model_name='absence',
            constraint=models.UniqueConstraint(fields=('tenant', 'employee', 'date'), name='absences_absence_emp_date_uniq'),
        ),
    ]
