# Generated by Django 4.2.30 on 2026-08-03 21:36

import apps.absences.models
import apps.absences.validators
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0004_alter_employee_profile_photo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('absences', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='absence',
            name='date',
            field=models.DateField(verbose_name='date'),
        ),
        migrations.AlterField(
            model_name='absence',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='absences', to='employees.employee', verbose_name='employé'),
        ),
        migrations.AlterField(
            model_name='absence',
            name='employee_comment',
            field=models.TextField(blank=True, verbose_name="commentaire de l'employé"),
        ),
        migrations.AlterField(
            model_name='absence',
            name='is_auto_detected',
            field=models.BooleanField(default=False, verbose_name='détectée automatiquement'),
        ),
        migrations.AlterField(
            model_name='absence',
            name='justification_file',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to=apps.absences.models.justification_path, validators=[apps.absences.validators.validate_justification_file], verbose_name='justificatif'),
        ),
        migrations.AlterField(
            model_name='absence',
            name='reason',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='absences', to='absences.absencereason', verbose_name='motif'),
        ),
        migrations.AlterField(
            model_name='absence',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='validé le'),
        ),
        migrations.AlterField(
            model_name='absence',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='absences_reviewed', to=settings.AUTH_USER_MODEL, verbose_name='validé par'),
        ),
        migrations.AlterField(
            model_name='absence',
            name='reviewer_comment',
            field=models.TextField(blank=True, verbose_name='commentaire du valideur'),
        ),
        migrations.AlterField(
            model_name='absence',
            name='status',
            field=models.CharField(choices=[('UNJUSTIFIED', 'Non justifiée'), ('PENDING_REVIEW', 'En attente de validation'), ('JUSTIFIED', 'Justifiée'), ('REJECTED', 'Rejetée')], default='UNJUSTIFIED', max_length=15, verbose_name='statut'),
        ),
        migrations.AlterField(
            model_name='absencereason',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='actif'),
        ),
        migrations.AlterField(
            model_name='absencereason',
            name='name',
            field=models.CharField(max_length=255, verbose_name='nom'),
        ),
        migrations.AlterField(
            model_name='absencereason',
            name='requires_certificate',
            field=models.BooleanField(default=False, verbose_name='certificat requis'),
        ),
    ]
