# Generated by Django 4.2.30 on 2026-08-05 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('absences', '0002_alter_absence_date_alter_absence_employee_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='absence',
            name='custom_reason',
            field=models.CharField(blank=True, max_length=255, verbose_name='motif personnalisé'),
        ),
    ]
