# Generated by Django 4.2.30 on 2026-08-05 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('absences', '0003_absence_custom_reason'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='absence',
            name='justification_file',
        ),
    ]
