# Generated by Django 4.2.30 on 2026-08-02 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_passwordresettoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='lockout_count',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
