# Generated by Django 4.2.30 on 2026-08-03 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_user_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('SUPER_ADMIN', 'Super Administrateur'), ('ADMIN', 'Administrateur'), ('MANAGER', 'Manager'), ('EMPLOYEE', 'Employé')], default='EMPLOYEE', max_length=20),
        ),
    ]
