# Generated by Django 4.2.30 on 2026-08-03 21:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0005_alter_employee_birth_date_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('leaves', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='holiday',
            name='date',
            field=models.DateField(verbose_name='date'),
        ),
        migrations.AlterField(
            model_name='holiday',
            name='is_recurring',
            field=models.BooleanField(default=True, verbose_name='récurrent'),
        ),
        migrations.AlterField(
            model_name='holiday',
            name='name',
            field=models.CharField(max_length=255, verbose_name='nom'),
        ),
        migrations.AlterField(
            model_name='leave',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leaves', to='employees.employee', verbose_name='employé'),
        ),
        migrations.AlterField(
            model_name='leave',
            name='employee_comment',
            field=models.TextField(blank=True, verbose_name="commentaire de l'employé"),
        ),
        migrations.AlterField(
            model_name='leave',
            name='end_date',
            field=models.DateField(verbose_name='date de fin'),
        ),
        migrations.AlterField(
            model_name='leave',
            name='leave_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='leaves', to='leaves.leavetype', verbose_name='type de congé'),
        ),
        migrations.AlterField(
            model_name='leave',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='validé le'),
        ),
        migrations.AlterField(
            model_name='leave',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leaves_reviewed', to=settings.AUTH_USER_MODEL, verbose_name='validé par'),
        ),
        migrations.AlterField(
            model_name='leave',
            name='reviewer_comment',
            field=models.TextField(blank=True, verbose_name='commentaire du valideur'),
        ),
        migrations.AlterField(
            model_name='leave',
            name='start_date',
            field=models.DateField(verbose_name='date de début'),
        ),
        migrations.AlterField(
            model_name='leave',
            name='status',
            field=models.CharField(choices=[('PENDING', 'En attente'), ('APPROVED', 'Approuvé'), ('REJECTED', 'Rejeté'), ('CANCELLED', 'Annulé')], default='PENDING', max_length=10, verbose_name='statut'),
        ),
        migrations.AlterField(
            model_name='leave',
            name='working_days',
            field=models.DecimalField(decimal_places=1, max_digits=5, verbose_name='jours ouvrés'),
        ),
        migrations.AlterField(
            model_name='leavetype',
            name='deducts_from_balance',
            field=models.BooleanField(default=True, verbose_name='déduit du solde'),
        ),
        migrations.AlterField(
            model_name='leavetype',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='actif'),
        ),
        migrations.AlterField(
            model_name='leavetype',
            name='name',
            field=models.CharField(max_length=255, verbose_name='nom'),
        ),
        migrations.AlterField(
            model_name='leavetype',
            name='requires_justification',
            field=models.BooleanField(default=False, verbose_name='justificatif requis'),
        ),
    ]
