# Generated by Django 4.2.30 on 2026-08-02 12:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Backup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('filename', models.CharField(max_length=255)),
                ('size_bytes', models.BigIntegerField(default=0)),
                ('checksum_sha256', models.CharField(blank=True, max_length=64)),
                ('is_manual', models.BooleanField(default=False)),
                ('comment', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('SUCCESS', 'Réussie'), ('FAILED', 'Échouée')], default='SUCCESS', max_length=10)),
                ('error_message', models.TextField(blank=True)),
                ('secondary_path', models.CharField(blank=True, max_length=500)),
                ('last_verified_at', models.DateTimeField(blank=True, null=True)),
                ('last_verification_ok', models.BooleanField(blank=True, null=True)),
                ('triggered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='backups_triggered', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
