# Generated by Django 4.2.30 on 2026-08-03 07:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0004_alter_employee_profile_photo'),
        ('agencies', '0005_alter_agency_photo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tenants', '0002_alter_organization_logo'),
        ('departments', '0004_alter_department_managers_alter_position_managers'),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255, verbose_name='titre')),
                ('content', models.TextField(verbose_name='contenu')),
                ('publish_at', models.DateTimeField(verbose_name='date de publication')),
                ('expire_at', models.DateTimeField(blank=True, null=True, verbose_name="date d'expiration")),
                ('agencies', models.ManyToManyField(blank=True, related_name='announcements', to='agencies.agency')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('departments', models.ManyToManyField(blank=True, related_name='announcements', to='departments.department')),
                ('employees', models.ManyToManyField(blank=True, related_name='announcements', to='employees.employee')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenants.organization')),
            ],
            options={
                'ordering': ['-publish_at'],
                'indexes': [models.Index(fields=['tenant', 'publish_at', 'expire_at'], name='announcemen_tenant__a566ec_idx')],
            },
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
