# Generated by Django 4.2.30 on 2026-08-03 21:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0004_alter_employee_profile_photo'),
        ('departments', '0004_alter_department_managers_alter_position_managers'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('agencies', '0006_alter_agency_options_alter_agency_address_and_more'),
        ('announcements', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='agencies',
            field=models.ManyToManyField(blank=True, related_name='announcements', to='agencies.agency', verbose_name='agences'),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='créée par'),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='departments',
            field=models.ManyToManyField(blank=True, related_name='announcements', to='departments.department', verbose_name='départements'),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='employees',
            field=models.ManyToManyField(blank=True, related_name='announcements', to='employees.employee', verbose_name='employés'),
        ),
    ]
