# Generated by Django 4.2.30 on 2026-08-01 12:30

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0003_alter_department_managers_alter_position_managers'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='department',
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='position',
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
