# Generated by Django 4.2.30 on 2026-08-01 03:10

import apps.tenants.models
import django.core.validators
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('legal_name', models.CharField(max_length=255, verbose_name='nom légal')),
                ('display_name', models.CharField(max_length=255, verbose_name='nom commercial')),
                ('slug', models.SlugField(unique=True)),
                ('org_type', models.CharField(choices=[('COMPANY', 'Entreprise'), ('SCHOOL', 'Établissement scolaire'), ('UNIVERSITY', 'Université'), ('RESTAURANT', 'Restaurant'), ('PHARMACY', 'Pharmacie'), ('HOSPITAL', 'Clinique / Hôpital'), ('NGO', 'ONG'), ('ADMIN', 'Administration publique'), ('ASSOCIATION', 'Association'), ('OTHER', 'Autre')], default='OTHER', max_length=20)),
                ('sector', models.CharField(blank=True, max_length=255, verbose_name="secteur d'activité")),
                ('country', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('address', models.TextField(blank=True)),
                ('postal_code', models.CharField(blank=True, max_length=20)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('website', models.URLField(blank=True)),
                ('employee_count_range', models.CharField(blank=True, choices=[('UNDER_10', '< 10'), ('10_50', '10 – 50'), ('50_200', '50 – 200'), ('200_500', '200 – 500'), ('OVER_500', '> 500')], max_length=10)),
                ('timezone', models.CharField(default='UTC', max_length=64)),
                ('language', models.CharField(choices=[('fr', 'Français'), ('en', 'English'), ('ar', 'العربية')], default='fr', max_length=2)),
                ('date_format', models.CharField(choices=[('DD/MM/YYYY', 'JJ/MM/AAAA'), ('MM/DD/YYYY', 'MM/JJ/AAAA'), ('YYYY-MM-DD', 'AAAA-MM-JJ')], default='DD/MM/YYYY', max_length=10)),
                ('time_format', models.CharField(choices=[('24H', '24h'), ('12H', '12h (AM/PM)')], default='24H', max_length=3)),
                ('logo', models.ImageField(blank=True, null=True, upload_to=apps.tenants.models.organization_logo_path)),
                ('primary_color', models.CharField(default='#0D2137', max_length=7, validators=[django.core.validators.RegexValidator(message='La couleur doit être un code hexadécimal valide, ex. #1565C0.', regex='^#[0-9A-Fa-f]{6}$')])),
                ('secondary_color', models.CharField(default='#1565C0', max_length=7, validators=[django.core.validators.RegexValidator(message='La couleur doit être un code hexadécimal valide, ex. #1565C0.', regex='^#[0-9A-Fa-f]{6}$')])),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('SUSPENDED', 'Suspendue'), ('EXPIRED', 'Expirée'), ('DELETED', 'Supprimée')], default='ACTIVE', max_length=10)),
                ('settings', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ['display_name'],
            },
        ),
    ]
