# Generated by Django 4.2.30 on 2026-08-01 13:26

import apps.tenants.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='logo',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to=apps.tenants.models.organization_logo_path),
        ),
    ]
