# Generated by Django 4.2.30 on 2026-08-03 21:36

import apps.tenants.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0002_alter_organization_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='address',
            field=models.TextField(blank=True, verbose_name='adresse'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='city',
            field=models.CharField(max_length=100, verbose_name='ville'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='country',
            field=models.CharField(max_length=100, verbose_name='pays'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='date_format',
            field=models.CharField(choices=[('DD/MM/YYYY', 'JJ/MM/AAAA'), ('MM/DD/YYYY', 'MM/JJ/AAAA'), ('YYYY-MM-DD', 'AAAA-MM-JJ')], default='DD/MM/YYYY', max_length=10, verbose_name='format de date'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='e-mail'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='employee_count_range',
            field=models.CharField(blank=True, choices=[('UNDER_10', '< 10'), ('10_50', '10 – 50'), ('50_200', '50 – 200'), ('200_500', '200 – 500'), ('OVER_500', '> 500')], max_length=10, verbose_name='effectif'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='language',
            field=models.CharField(choices=[('fr', 'Français'), ('en', 'English'), ('ar', 'العربية')], default='fr', max_length=2, verbose_name='langue'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='logo',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to=apps.tenants.models.organization_logo_path, verbose_name='logo'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='org_type',
            field=models.CharField(choices=[('COMPANY', 'Entreprise'), ('SCHOOL', 'Établissement scolaire'), ('UNIVERSITY', 'Université'), ('RESTAURANT', 'Restaurant'), ('PHARMACY', 'Pharmacie'), ('HOSPITAL', 'Clinique / Hôpital'), ('NGO', 'ONG'), ('ADMIN', 'Administration publique'), ('ASSOCIATION', 'Association'), ('OTHER', 'Autre')], default='OTHER', max_length=20, verbose_name="type d'organisation"),
        ),
        migrations.AlterField(
            model_name='organization',
            name='phone',
            field=models.CharField(blank=True, max_length=30, verbose_name='téléphone'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='postal_code',
            field=models.CharField(blank=True, max_length=20, verbose_name='code postal'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='primary_color',
            field=models.CharField(default='#0D2137', max_length=7, validators=[django.core.validators.RegexValidator(message='La couleur doit être un code hexadécimal valide, ex. #1565C0.', regex='^#[0-9A-Fa-f]{6}$')], verbose_name='couleur principale'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='secondary_color',
            field=models.CharField(default='#1565C0', max_length=7, validators=[django.core.validators.RegexValidator(message='La couleur doit être un code hexadécimal valide, ex. #1565C0.', regex='^#[0-9A-Fa-f]{6}$')], verbose_name='couleur secondaire'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='slug',
            field=models.SlugField(unique=True, verbose_name='identifiant (slug)'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('SUSPENDED', 'Suspendue'), ('EXPIRED', 'Expirée'), ('DELETED', 'Supprimée')], default='ACTIVE', max_length=10, verbose_name='statut'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='time_format',
            field=models.CharField(choices=[('24H', '24h'), ('12H', '12h (AM/PM)')], default='24H', max_length=3, verbose_name="format d'heure"),
        ),
        migrations.AlterField(
            model_name='organization',
            name='timezone',
            field=models.CharField(default='UTC', max_length=64, verbose_name='fuseau horaire'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='website',
            field=models.URLField(blank=True, verbose_name='site web'),
        ),
    ]
