# Generated by Django 4.2.30 on 2026-08-07 02:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0003_alter_organization_address_alter_organization_city_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organization',
            name='logo',
        ),
    ]
