# Generated by Django 4.2.30 on 2026-08-01 03:36

import apps.agencies.models
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agency',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, verbose_name='nom')),
                ('code', models.CharField(max_length=20, verbose_name='code')),
                ('agency_type', models.CharField(choices=[('HEADQUARTERS', 'Siège'), ('BRANCH', 'Agence'), ('SUBSIDIARY', 'Filiale'), ('WAREHOUSE', 'Entrepôt'), ('CONSTRUCTION_SITE', 'Chantier'), ('REMOTE', 'Télétravail'), ('OTHER', 'Autre')], default='BRANCH', max_length=20)),
                ('address', models.TextField(blank=True)),
                ('city', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('latitude', models.DecimalField(decimal_places=7, max_digits=10, validators=[django.core.validators.MinValueValidator(-90), django.core.validators.MaxValueValidator(90)])),
                ('longitude', models.DecimalField(decimal_places=7, max_digits=10, validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)])),
                ('radius_meters', models.PositiveIntegerField(default=200, validators=[django.core.validators.MinValueValidator(50), django.core.validators.MaxValueValidator(5000)], verbose_name='rayon GPS (m)')),
                ('extra_zones', models.JSONField(blank=True, default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('allow_offline_clocking', models.BooleanField(default=True, help_text="Surcharge le paramètre par défaut de l'organisation.", verbose_name='pointage hors ligne autorisé')),
                ('photo', models.ImageField(blank=True, null=True, upload_to=apps.agencies.models.agency_photo_path)),
                ('notes', models.TextField(blank=True)),
                ('responsible', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agencies_managed', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenants.organization')),
            ],
            options={
                'verbose_name_plural': 'agencies',
                'ordering': ['name'],
            },
        ),
        migrations.AddConstraint(
            model_name='agency',
            constraint=models.UniqueConstraint(fields=('tenant', 'code'), name='agencies_agency_tenant_code_uniq'),
        ),
    ]
