# Generated by Django 4.2.30 on 2026-08-01 12:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0001_initial'),
        ('agencies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='agency',
            name='default_schedule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agencies', to='schedules.schedule'),
        ),
    ]
