# Generated by Django 4.2.30 on 2026-08-01 12:26

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('agencies', '0002_agency_default_schedule'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='agency',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
