# Generated by Django 4.2.30 on 2026-08-01 12:30

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('agencies', '0003_alter_agency_managers'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='agency',
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
