# Generated by Django 4.2.30 on 2026-08-01 13:26

import apps.agencies.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agencies', '0004_alter_agency_managers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agency',
            name='photo',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to=apps.agencies.models.agency_photo_path),
        ),
    ]
