# Generated by Django 4.2.30 on 2026-08-03 21:36

import apps.agencies.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('schedules', '0003_alter_employeescheduleassignment_managers_and_more'),
        ('agencies', '0005_alter_agency_photo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agency',
            options={'ordering': ['name'], 'verbose_name': 'agence', 'verbose_name_plural': 'agences'},
        ),
        migrations.AlterField(
            model_name='agency',
            name='address',
            field=models.TextField(blank=True, verbose_name='adresse'),
        ),
        migrations.AlterField(
            model_name='agency',
            name='agency_type',
            field=models.CharField(choices=[('HEADQUARTERS', 'Siège'), ('BRANCH', 'Agence'), ('SUBSIDIARY', 'Filiale'), ('WAREHOUSE', 'Entrepôt'), ('CONSTRUCTION_SITE', 'Chantier'), ('REMOTE', 'Télétravail'), ('OTHER', 'Autre')], default='BRANCH', max_length=20, verbose_name="type d'agence"),
        ),
        migrations.AlterField(
            model_name='agency',
            name='city',
            field=models.CharField(max_length=100, verbose_name='ville'),
        ),
        migrations.AlterField(
            model_name='agency',
            name='country',
            field=models.CharField(max_length=100, verbose_name='pays'),
        ),
        migrations.AlterField(
            model_name='agency',
            name='default_schedule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agencies', to='schedules.schedule', verbose_name='horaire par défaut'),
        ),
        migrations.AlterField(
            model_name='agency',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='e-mail'),
        ),
        migrations.AlterField(
            model_name='agency',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='active'),
        ),
        migrations.AlterField(
            model_name='agency',
            name='notes',
            field=models.TextField(blank=True, verbose_name='notes'),
        ),
        migrations.AlterField(
            model_name='agency',
            name='phone',
            field=models.CharField(blank=True, max_length=30, verbose_name='téléphone'),
        ),
        migrations.AlterField(
            model_name='agency',
            name='photo',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to=apps.agencies.models.agency_photo_path, verbose_name='photo'),
        ),
        migrations.AlterField(
            model_name='agency',
            name='responsible',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agencies_managed', to=settings.AUTH_USER_MODEL, verbose_name='responsable'),
        ),
    ]
