# Generated by Django 4.2.30 on 2026-08-15 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agencies', '0006_alter_agency_options_alter_agency_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agency',
            name='qr_token',
            field=models.CharField(blank=True, db_index=True, max_length=64, verbose_name='jeton QR'),
        ),
    ]
