# Generated by Django 4.2.30 on 2026-08-01 12:53

import apps.attendance.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('agencies', '0004_alter_agency_managers'),
        ('tenants', '0001_initial'),
        ('employees', '0003_alter_employee_managers'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('clock_type', models.CharField(choices=[('ARRIVAL', 'Arrivée'), ('BREAK_START', 'Départ pause'), ('BREAK_END', 'Retour pause'), ('DEPARTURE', 'Départ')], max_length=15)),
                ('clock_date', models.DateField()),
                ('server_time', models.DateTimeField()),
                ('client_time', models.DateTimeField(blank=True, null=True)),
                ('latitude', models.DecimalField(decimal_places=7, max_digits=10)),
                ('longitude', models.DecimalField(decimal_places=7, max_digits=10)),
                ('gps_accuracy', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('is_gps_mocked', models.BooleanField(default=False)),
                ('photo', models.ImageField(upload_to=apps.attendance.models.attendance_photo_path)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=255)),
                ('device_type', models.CharField(blank=True, max_length=20)),
                ('scheduled_time', models.DateTimeField(blank=True, null=True)),
                ('late_minutes', models.PositiveIntegerField(blank=True, null=True)),
                ('early_leave_minutes', models.PositiveIntegerField(blank=True, null=True)),
                ('overtime_minutes', models.PositiveIntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ON_TIME', "À l'heure"), ('LATE', 'Retard'), ('EARLY_LEAVE', 'Départ anticipé'), ('OVERTIME', 'Heures supplémentaires'), ('OUT_OF_SCHEDULE', 'Hors horaire'), ('PENDING_VALIDATION', 'En attente de validation'), ('MANUALLY_VALIDATED', 'Validé manuellement'), ('REJECTED', 'Rejeté')], max_length=20)),
                ('mode', models.CharField(choices=[('ONLINE', 'En ligne'), ('OFFLINE', 'Hors ligne')], default='ONLINE', max_length=10)),
                ('synced_at', models.DateTimeField(blank=True, null=True)),
                ('is_validated', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attendances', to='agencies.agency')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attendances', to='employees.employee')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenants.organization')),
                ('validated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendances_validated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-server_time'],
                'indexes': [models.Index(fields=['tenant', 'employee', 'clock_date'], name='attendance_emp_date_idx'), models.Index(fields=['tenant', 'agency', 'clock_date'], name='attendance_agency_date_idx')],
            },
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddConstraint(
            model_name='attendance',
            constraint=models.UniqueConstraint(fields=('tenant', 'employee', 'clock_date', 'clock_type'), name='attendance_one_per_day_type'),
        ),
    ]
