# Generated by Django 4.2.30 on 2026-08-01 13:26

import apps.attendance.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='photo',
            field=models.ImageField(max_length=255, upload_to=apps.attendance.models.attendance_photo_path),
        ),
    ]
