# Generated by Django 4.2.30 on 2026-08-03 06:39

from django.db import migrations


def delete_photo_files(apps, schema_editor):
    """La photo au pointage est retirée du cahier des charges (remplacée par
    une carte GPS interactive) — sur demande explicite : supprimer aussi les
    fichiers déjà stockés, pas seulement arrêter d'en exiger de nouveaux."""
    Attendance = apps.get_model("attendance", "Attendance")
    for attendance in Attendance._default_manager.exclude(photo="").only("photo"):
        attendance.photo.delete(save=False)


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_alter_attendance_photo'),
    ]

    operations = [
        migrations.RunPython(delete_photo_files, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='attendance',
            name='photo',
        ),
    ]
