# Generated by Django 4.2.30 on 2026-08-03 07:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0003_alter_employeescheduleassignment_managers_and_more'),
        ('attendance', '0003_remove_attendance_photo'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='attendance',
            name='attendance_one_per_day_type',
        ),
        migrations.AddField(
            model_name='attendance',
            name='schedule_slot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendances', to='schedules.scheduleslot'),
        ),
        migrations.AddConstraint(
            model_name='attendance',
            constraint=models.UniqueConstraint(fields=('tenant', 'employee', 'clock_date', 'clock_type', 'schedule_slot'), name='attendance_one_per_day_type_slot'),
        ),
    ]
