# Generated by Django 4.2.30 on 2026-08-15 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0004_remove_attendance_attendance_one_per_day_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='source',
            field=models.CharField(choices=[('APP', 'Application'), ('QR', 'Code QR')], default='APP', max_length=10),
        ),
    ]
