# Generated by Django 4.2.30 on 2026-08-02 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AIProviderConfig',
        ),
    ]
