# Generated by Django 4.2.30 on 2026-08-03 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0002_delete_aiproviderconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='aimessage',
            name='suggestions',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
