# Generated by Django 4.2.30 on 2026-08-01 12:10

import apps.core.encrypted_fields
import apps.employees.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
        ('departments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('agencies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('matricule', models.CharField(blank=True, max_length=30)),
                ('preferred_name', models.CharField(blank=True, max_length=150, verbose_name="nom d'usage")),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(choices=[('MALE', 'Masculin'), ('FEMALE', 'Féminin'), ('UNSPECIFIED', 'Non renseigné')], default='UNSPECIFIED', max_length=15)),
                ('nationality', models.CharField(blank=True, max_length=100)),
                ('id_number', apps.core.encrypted_fields.EncryptedCharField(blank=True, max_length=500)),
                ('profile_photo', models.ImageField(blank=True, null=True, upload_to=apps.employees.models.employee_photo_path)),
                ('personal_email', models.EmailField(blank=True, max_length=254)),
                ('work_phone', models.CharField(blank=True, max_length=30)),
                ('personal_phone', models.CharField(blank=True, max_length=30)),
                ('home_address', models.TextField(blank=True)),
                ('emergency_contact_name', models.CharField(blank=True, max_length=255)),
                ('emergency_contact_phone', models.CharField(blank=True, max_length=30)),
                ('contract_type', models.CharField(choices=[('CDI', 'CDI'), ('CDD', 'CDD'), ('INTERIM', 'Intérim'), ('INTERNSHIP', 'Stage'), ('VOLUNTEER', 'Bénévole'), ('CONSULTANT', 'Consultant'), ('OTHER', 'Autre')], default='CDI', max_length=15)),
                ('hire_date', models.DateField()),
                ('contract_end_date', models.DateField(blank=True, null=True)),
                ('annual_leave_days', models.DecimalField(decimal_places=1, default=0, max_digits=5, verbose_name='droit aux congés (j/an)')),
                ('leave_balance', models.DecimalField(decimal_places=1, default=0, max_digits=5, verbose_name='solde congés (j)')),
                ('status', models.CharField(choices=[('ACTIVE', 'Actif'), ('SUSPENDED', 'Suspendu'), ('ON_LEAVE', 'En congé'), ('ARCHIVED', 'Archivé')], default='ACTIVE', max_length=10)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='employees', to='departments.department')),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='direct_reports', to=settings.AUTH_USER_MODEL)),
                ('position', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='employees', to='departments.position')),
                ('primary_agency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='employees_primary', to='agencies.agency')),
                ('secondary_agencies', models.ManyToManyField(blank=True, related_name='employees_secondary', to='agencies.agency')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenants.organization')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='employee_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['matricule'],
            },
        ),
        migrations.AddConstraint(
            model_name='employee',
            constraint=models.UniqueConstraint(fields=('tenant', 'matricule'), name='employees_employee_tenant_matricule_uniq'),
        ),
    ]
