# Generated by Django 4.2.30 on 2026-08-01 13:26

import apps.employees.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_alter_employee_managers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='profile_photo',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to=apps.employees.models.employee_photo_path),
        ),
    ]
