# Generated by Django 4.2.30 on 2026-08-03 21:36

import apps.core.encrypted_fields
import apps.employees.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('departments', '0005_alter_department_code_and_more'),
        ('agencies', '0006_alter_agency_options_alter_agency_address_and_more'),
        ('employees', '0004_alter_employee_profile_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='birth_date',
            field=models.DateField(blank=True, null=True, verbose_name='date de naissance'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='contract_end_date',
            field=models.DateField(blank=True, null=True, verbose_name='date de fin de contrat'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='contract_type',
            field=models.CharField(choices=[('CDI', 'CDI'), ('CDD', 'CDD'), ('INTERIM', 'Intérim'), ('INTERNSHIP', 'Stage'), ('VOLUNTEER', 'Bénévole'), ('CONSULTANT', 'Consultant'), ('OTHER', 'Autre')], default='CDI', max_length=15, verbose_name='type de contrat'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='employees', to='departments.department', verbose_name='département'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='emergency_contact_name',
            field=models.CharField(blank=True, max_length=255, verbose_name="contact d'urgence — nom"),
        ),
        migrations.AlterField(
            model_name='employee',
            name='emergency_contact_phone',
            field=models.CharField(blank=True, max_length=30, verbose_name="contact d'urgence — téléphone"),
        ),
        migrations.AlterField(
            model_name='employee',
            name='gender',
            field=models.CharField(choices=[('MALE', 'Masculin'), ('FEMALE', 'Féminin'), ('UNSPECIFIED', 'Non renseigné')], default='UNSPECIFIED', max_length=15, verbose_name='genre'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='hire_date',
            field=models.DateField(verbose_name="date d'entrée"),
        ),
        migrations.AlterField(
            model_name='employee',
            name='home_address',
            field=models.TextField(blank=True, verbose_name='adresse personnelle'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='id_number',
            field=apps.core.encrypted_fields.EncryptedCharField(blank=True, max_length=500, verbose_name="numéro de pièce d'identité"),
        ),
        migrations.AlterField(
            model_name='employee',
            name='manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='direct_reports', to=settings.AUTH_USER_MODEL, verbose_name='manager'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='matricule',
            field=models.CharField(blank=True, max_length=30, verbose_name='matricule'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='nationality',
            field=models.CharField(blank=True, max_length=100, verbose_name='nationalité'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='personal_email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='e-mail personnel'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='personal_phone',
            field=models.CharField(blank=True, max_length=30, verbose_name='téléphone personnel'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='position',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='employees', to='departments.position', verbose_name='poste'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='primary_agency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='employees_primary', to='agencies.agency', verbose_name='agence principale'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='profile_photo',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to=apps.employees.models.employee_photo_path, verbose_name='photo de profil'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='secondary_agencies',
            field=models.ManyToManyField(blank=True, related_name='employees_secondary', to='agencies.agency', verbose_name='agences secondaires'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Actif'), ('SUSPENDED', 'Suspendu'), ('ON_LEAVE', 'En congé'), ('ARCHIVED', 'Archivé')], default='ACTIVE', max_length=10, verbose_name='statut'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='work_phone',
            field=models.CharField(blank=True, max_length=30, verbose_name='téléphone professionnel'),
        ),
    ]
