# Generated by Django 4.2.30 on 2026-08-07 02:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0005_alter_employee_birth_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='profile_photo',
        ),
    ]
