# Generated by Django 4.2.30 on 2026-08-01 12:22

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('schedule_type', models.CharField(choices=[('FIXED', 'Horaire fixe'), ('TEAM', 'Équipe (rotation)'), ('CUSTOM', 'Personnalisé'), ('TEACHER', 'Enseignant')], default='FIXED', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('late_tolerance_minutes', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('early_leave_tolerance_minutes', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('overtime_threshold_minutes', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenants.organization')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ScheduleSlot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('weekday', models.IntegerField(choices=[(0, 'Lundi'), (1, 'Mardi'), (2, 'Mercredi'), (3, 'Jeudi'), (4, 'Vendredi'), (5, 'Samedi'), (6, 'Dimanche')])),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('break_start_time', models.TimeField(blank=True, null=True)),
                ('break_end_time', models.TimeField(blank=True, null=True)),
                ('clock_in_window_before_minutes', models.PositiveSmallIntegerField(default=30)),
                ('clock_in_window_after_minutes', models.PositiveSmallIntegerField(default=120)),
                ('clock_out_window_before_minutes', models.PositiveSmallIntegerField(default=30)),
                ('clock_out_window_after_minutes', models.PositiveSmallIntegerField(default=180)),
                ('subject', models.CharField(blank=True, max_length=255, verbose_name='matière')),
                ('room', models.CharField(blank=True, max_length=100, verbose_name='salle')),
                ('group_label', models.CharField(blank=True, max_length=100, verbose_name='groupe')),
                ('is_cancelled', models.BooleanField(default=False)),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='schedules.schedule')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenants.organization')),
            ],
            options={
                'ordering': ['weekday', 'start_time'],
            },
        ),
        migrations.CreateModel(
            name='EmployeeScheduleAssignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('valid_from', models.DateField()),
                ('valid_until', models.DateField(blank=True, null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_assignments', to='employees.employee')),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='employee_assignments', to='schedules.schedule')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenants.organization')),
            ],
            options={
                'ordering': ['-valid_from'],
            },
        ),
        migrations.AddConstraint(
            model_name='schedule',
            constraint=models.UniqueConstraint(fields=('tenant', 'name'), name='schedules_schedule_tenant_name_uniq'),
        ),
    ]
