# Generated by Django 4.2.30 on 2026-08-01 12:30

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0002_alter_employeescheduleassignment_managers_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='employeescheduleassignment',
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='schedule',
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='scheduleslot',
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
