# Generated by Django 4.2.30 on 2026-08-03 21:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0005_alter_employee_birth_date_and_more'),
        ('schedules', '0003_alter_employeescheduleassignment_managers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeescheduleassignment',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_assignments', to='employees.employee', verbose_name='employé'),
        ),
        migrations.AlterField(
            model_name='employeescheduleassignment',
            name='schedule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='employee_assignments', to='schedules.schedule', verbose_name='horaire'),
        ),
        migrations.AlterField(
            model_name='employeescheduleassignment',
            name='valid_from',
            field=models.DateField(verbose_name='valide à partir du'),
        ),
        migrations.AlterField(
            model_name='employeescheduleassignment',
            name='valid_until',
            field=models.DateField(blank=True, null=True, verbose_name="valide jusqu'au"),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='early_leave_tolerance_minutes',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='tolérance de départ anticipé (min)'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='actif'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='late_tolerance_minutes',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='tolérance de retard (min)'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='name',
            field=models.CharField(max_length=255, verbose_name='nom'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='overtime_threshold_minutes',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name="seuil d'heures supplémentaires (min)"),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='schedule_type',
            field=models.CharField(choices=[('FIXED', 'Horaire fixe'), ('TEAM', 'Équipe (rotation)'), ('CUSTOM', 'Personnalisé'), ('TEACHER', 'Enseignant')], default='FIXED', max_length=10, verbose_name="type d'horaire"),
        ),
        migrations.AlterField(
            model_name='scheduleslot',
            name='break_end_time',
            field=models.TimeField(blank=True, null=True, verbose_name='fin de pause'),
        ),
        migrations.AlterField(
            model_name='scheduleslot',
            name='break_start_time',
            field=models.TimeField(blank=True, null=True, verbose_name='début de pause'),
        ),
        migrations.AlterField(
            model_name='scheduleslot',
            name='clock_in_window_after_minutes',
            field=models.PositiveSmallIntegerField(default=120, verbose_name="fenêtre d'arrivée après (min)"),
        ),
        migrations.AlterField(
            model_name='scheduleslot',
            name='clock_in_window_before_minutes',
            field=models.PositiveSmallIntegerField(default=30, verbose_name="fenêtre d'arrivée avant (min)"),
        ),
        migrations.AlterField(
            model_name='scheduleslot',
            name='clock_out_window_after_minutes',
            field=models.PositiveSmallIntegerField(default=180, verbose_name='fenêtre de départ après (min)'),
        ),
        migrations.AlterField(
            model_name='scheduleslot',
            name='clock_out_window_before_minutes',
            field=models.PositiveSmallIntegerField(default=30, verbose_name='fenêtre de départ avant (min)'),
        ),
        migrations.AlterField(
            model_name='scheduleslot',
            name='end_time',
            field=models.TimeField(verbose_name='heure de fin'),
        ),
        migrations.AlterField(
            model_name='scheduleslot',
            name='is_cancelled',
            field=models.BooleanField(default=False, verbose_name='annulé'),
        ),
        migrations.AlterField(
            model_name='scheduleslot',
            name='schedule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='schedules.schedule', verbose_name='horaire'),
        ),
        migrations.AlterField(
            model_name='scheduleslot',
            name='start_time',
            field=models.TimeField(verbose_name='heure de début'),
        ),
        migrations.AlterField(
            model_name='scheduleslot',
            name='weekday',
            field=models.IntegerField(choices=[(0, 'Lundi'), (1, 'Mardi'), (2, 'Mercredi'), (3, 'Jeudi'), (4, 'Vendredi'), (5, 'Samedi'), (6, 'Dimanche')], verbose_name='jour de la semaine'),
        ),
    ]
