# Generated by Django 4.2.30 on 2026-08-07 01:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0004_alter_employeescheduleassignment_employee_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scheduleslot',
            name='group_label',
        ),
        migrations.RemoveField(
            model_name='scheduleslot',
            name='room',
        ),
        migrations.RemoveField(
            model_name='scheduleslot',
            name='subject',
        ),
    ]
