# Generated by Django 4.2.30 on 2026-08-21 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0005_remove_scheduleslot_group_label_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='term',
            field=models.CharField(blank=True, max_length=100, verbose_name='période (trimestre/semestre)'),
        ),
        migrations.AddField(
            model_name='scheduleslot',
            name='room',
            field=models.CharField(blank=True, max_length=100, verbose_name='salle'),
        ),
        migrations.AddField(
            model_name='scheduleslot',
            name='student_group',
            field=models.CharField(blank=True, max_length=150, verbose_name='groupe / classe'),
        ),
        migrations.AddField(
            model_name='scheduleslot',
            name='subject',
            field=models.CharField(blank=True, max_length=150, verbose_name='matière'),
        ),
        migrations.AddField(
            model_name='scheduleslot',
            name='substitute_note',
            field=models.CharField(blank=True, max_length=255, verbose_name='remplacement'),
        ),
    ]
