# Generated by Django 4.2.30 on 2026-08-28 22:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0006_remove_employee_profile_photo'),
        ('tenants', '0004_remove_organization_logo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('schedules', '0006_schedule_term_scheduleslot_room_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SlotException',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField(verbose_name='date')),
                ('kind', models.CharField(choices=[('CANCELLED', 'Annulé'), ('SUBSTITUTED', 'Remplacé')], max_length=12, verbose_name='type')),
                ('substitute_note', models.CharField(blank=True, max_length=255, verbose_name='remplaçant (externe)')),
                ('reason', models.CharField(blank=True, max_length=255, verbose_name='motif')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('original_employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='employees.employee', verbose_name='enseignant prévu')),
                ('slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exceptions', to='schedules.scheduleslot', verbose_name='créneau')),
                ('substitute_employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='employees.employee', verbose_name='remplaçant (interne)')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenants.organization')),
            ],
            options={
                'ordering': ['-date'],
            },
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddConstraint(
            model_name='slotexception',
            constraint=models.UniqueConstraint(fields=('tenant', 'slot', 'date'), name='schedules_slotexception_slot_date_uniq'),
        ),
    ]
